# Generated by Django 4.1.7 on 2023-03-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_contact_name_contact_fullname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
